README skeleton with proposed review process
cafana/.github pull request #1
Opened 2022-12-07 20:29 UTC by chenel

2022-12-07 21:16 UTC, FernandaPsihas requested changes
I think the slack channel name has changed in only one of the organizations, maybe we can decide which one to keep and change it here if necessary. Otherwise I think this is really good.

2022-12-07 22:12 UTC, PetrilloAtWork reviewed
A few suggestions (the last one needs check and extension).

2022-12-07 22:12 UTC, PetrilloAtWork commented on profile/README.md
> +Current applications include efforts on NOvA as well as users from the [DUNE](https://www.dunescience.org/) and [SBN](https://sbn.fnal.gov/) collaborations.
SBN is not, as far as I know, a "collaboration":
```suggestion
Current applications include efforts on NOvA as well as users from the [DUNE collaboration](https://www.dunescience.org/) and the [Fermilab SBN program](https://sbn.fnal.gov/).
```

2022-12-07 22:12 UTC, PetrilloAtWork commented on profile/README.md
> +More on the history, design, and possible future directions of CAFAna may be found [here](https://arxiv.org/abs/2203.13768).
```suggestion
More on the history, design, and possible future directions of CAFAna may be found at [arXiv:2203.13768 [hep-ex]](https://arxiv.org/abs/2203.13768).
```

2022-12-07 22:12 UTC, PetrilloAtWork commented on profile/README.md
> +This will require a specialization of the workhorse `_Var` , `_Cut`, `_Weight`, and `Spectrum` types using a `StandardRecord` that fits their needs.
I would add some examples:
```suggestion
This will require a specialization of the workhorse `_Var` , `_Cut`, `_Weight`, and `Spectrum` types using a `StandardRecord` that fits their needs.
As examples, see the implementations by [SBN](https://github.com/SBNSoftware/sbnana/tree/develop/sbnana/CAFAna).
```
(I am not sure I am pointing to the appropriate SBN code, and we should have DUNE and NOvA examples)

2022-12-14 19:05 UTC, chenel commented on profile/README.md
> +This will require a specialization of the workhorse `_Var` , `_Cut`, `_Weight`, and `Spectrum` types using a `StandardRecord` that fits their needs.
Unfortunately for this purpose, the NOvA implementation is within a private repository in GitHub, so a link there won't serve much purpose.  But I can add a DUNE one easily.

2022-12-14 20:40 UTC, chenel commented
@FernandaPsihas :

> I think the slack channel name has changed in only one of the organizations, maybe we can decide which one to keep and change it here if necessary. Otherwise I think this is really good.

I'll leave it to @gavinsdavies to decide what we should call it in NOvA ultimately.  But anyways I updated the readme to have both names in it---that should hopefully be enough to go forwards for now?

(enough to "approve" this PR at least? 😄)

2023-01-11 21:10 UTC, FernandaPsihas approved these changes

2023-01-13 22:05 UTC, gavinsdavies approved these changes
Giving the NOvA approval

2023-01-16 11:45 UTC, merged